// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: proto/tlsservice.proto

package tlsservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TlsCommunicatorClient is the client API for TlsCommunicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TlsCommunicatorClient interface {
	Message(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
}

type tlsCommunicatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTlsCommunicatorClient(cc grpc.ClientConnInterface) TlsCommunicatorClient {
	return &tlsCommunicatorClient{cc}
}

func (c *tlsCommunicatorClient) Message(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/tlsservice.TlsCommunicator/message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TlsCommunicatorServer is the server API for TlsCommunicator service.
// All implementations must embed UnimplementedTlsCommunicatorServer
// for forward compatibility
type TlsCommunicatorServer interface {
	Message(context.Context, *Data) (*Data, error)
	mustEmbedUnimplementedTlsCommunicatorServer()
}

// UnimplementedTlsCommunicatorServer must be embedded to have forward compatible implementations.
type UnimplementedTlsCommunicatorServer struct {
}

func (UnimplementedTlsCommunicatorServer) Message(context.Context, *Data) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedTlsCommunicatorServer) mustEmbedUnimplementedTlsCommunicatorServer() {}

// UnsafeTlsCommunicatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TlsCommunicatorServer will
// result in compilation errors.
type UnsafeTlsCommunicatorServer interface {
	mustEmbedUnimplementedTlsCommunicatorServer()
}

func RegisterTlsCommunicatorServer(s grpc.ServiceRegistrar, srv TlsCommunicatorServer) {
	s.RegisterService(&TlsCommunicator_ServiceDesc, srv)
}

func _TlsCommunicator_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlsCommunicatorServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tlsservice.TlsCommunicator/message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlsCommunicatorServer).Message(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// TlsCommunicator_ServiceDesc is the grpc.ServiceDesc for TlsCommunicator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TlsCommunicator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tlsservice.TlsCommunicator",
	HandlerType: (*TlsCommunicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "message",
			Handler:    _TlsCommunicator_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tlsservice.proto",
}
