// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tlsservice.proto

package tlsservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	D                    string   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f872feb210429db, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "tlsservice.Data")
}

func init() { proto.RegisterFile("proto/tlsservice.proto", fileDescriptor_5f872feb210429db) }

var fileDescriptor_5f872feb210429db = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc9, 0x29, 0x2e, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x0b, 0x08,
	0x71, 0x21, 0x44, 0x94, 0x44, 0xb8, 0x58, 0x5c, 0x12, 0x4b, 0x12, 0x85, 0x78, 0xb8, 0x18, 0x53,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x18, 0x53, 0x8c, 0x1c, 0xb8, 0xf8, 0x43, 0x72, 0x8a,
	0x9d, 0xf3, 0x73, 0x73, 0x4b, 0xf3, 0x32, 0x93, 0x13, 0x4b, 0xf2, 0x8b, 0x84, 0x74, 0xb9, 0xd8,
	0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x04, 0xf4, 0x90, 0x8c, 0x04, 0xe9, 0x96, 0xc2,
	0x10, 0x71, 0xe2, 0x8b, 0xe2, 0xd1, 0x43, 0xb2, 0x39, 0x89, 0x0d, 0x6c, 0xb5, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x2c, 0x8b, 0x8c, 0x94, 0x00, 0x00, 0x00,
}
